CREATE TABLE GS_ROLE (
  ID_ROLE   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  ROLE_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE GS_LIMITS (
  ID_LIMITS    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  LIMIT_HOURS NUMBER(2) NOT NULL,
  LIMIT_MEETINGS  NUMBER(2) NOT NULL,
  CREATED_AT  DATE NOT NULL
);

CREATE TABLE GS_STATUS_RISK(
    ID_STATUS_RISK NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    STATUS_NAME_RISK VARCHAR2(15) NOT NULL
);

CREATE TABLE GS_USERS (
  ID_USER      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME_USER    VARCHAR2(100) NOT NULL,
  EMAIL_USER   VARCHAR2(255) NOT NULL UNIQUE,
  PASSWORD_USER VARCHAR2(255) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  ID_ROLE   NUMBER NOT NULL,
  ID_LIMITS  NUMBER NOT NULL,
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE)
    REFERENCES GS_ROLE (ID_ROLE),
  CONSTRAINT FK_USER_LIMITS FOREIGN KEY (ID_LIMITS)
    REFERENCES GS_LIMITS (ID_LIMITS)
);

CREATE TABLE GS_DAILY_LOGS (
  ID_LOG     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  WORK_HOURS NUMBER(2) NOT NULL,
  MEETINGS   NUMBER(2) NOT NULL,
  LOG_DATE   DATE NOT NULL,
  ID_USER    NUMBER NOT NULL,
  CONSTRAINT FK_LOG_USER FOREIGN KEY (ID_USER)
    REFERENCES GS_USERS (ID_USER)
);

CREATE TABLE GS_SCORES (
  ID_SCORES   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  DATE_SCORE  DATE NOT NULL,
  SCORE_VALUE   FLOAT(4) NOT NULL,
  TIME_RECOMMENDATION    NUMBER(2) NOT NULL,
  CREATED_AT DATE NOT NULL,
  ID_STATUS_RISK NUMBER NOT NULL,
  ID_USER  NUMBER NOT NULL,
  ID_LOG NUMBER NOT NULL,
  CONSTRAINT FK_SCORE_RISK FOREIGN KEY (ID_STATUS_RISK)
    REFERENCES GS_STATUS_RISK (ID_STATUS_RISK),
  CONSTRAINT FK_SCORE_USER FOREIGN KEY (ID_USER)
    REFERENCES GS_USERS (ID_USER),
  CONSTRAINT FK_SCORE_LOG FOREIGN KEY (ID_LOG)
    REFERENCES GS_DAILY_LOGS (ID_LOG)
);

CREATE TABLE GS_PREDICTIONS (
  ID_PREDICTION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  STRESS_PREDICTED FLOAT(2) NOT NULL,          
  MESSAGE  VARCHAR2(50) NOT NULL,
  DATE_PREDICTED   DATE NOT NULL,
  ID_USER NUMBER NOT NULL,
  ID_SCORES NUMBER,
  ID_STATUS_RISK NUMBER NOT NULL,
  CONSTRAINT FK_PRED_USER FOREIGN KEY (ID_USER)
    REFERENCES GS_USERS (ID_USER),
  CONSTRAINT FK_PRED_SCORES FOREIGN KEY (ID_SCORES)
    REFERENCES GS_SCORES (ID_SCORES),
  CONSTRAINT FK_PRED_RISK FOREIGN KEY (ID_STATUS_RISK)
    REFERENCES GS_STATUS_RISK (ID_STATUS_RISK)
);

DROP TABLE GS_BEHAVIOR_DATA CASCADE CONSTRAINT;
